### ISSUE TITLE
Link zurück zu Trefferliste?

### ISSUE THREAD

**Issue by arnese** [okfde/sehrgutachten#5]
Wenn ich aus einer Suche ein Gutachten anklicke, wird nicht zurück zur Trefferliste gelinkt. Wär vielleicht aber ganz sinnvoll?

**Comment by robbi5** [comment]
Damit könnten wir die Gutachtenseite nicht mehr lange und einfach im Edgeserver cachen. Bin für so Dinge eher ein Fan vom Browser Back Button :)

**Comment by arnese** [comment]
Gut :)
